"""empty message

Revision ID: 6576ea50d75d
Revises: e56cd59c65d3
Create Date: 2023-08-22 01:19:12.889666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6576ea50d75d'
down_revision = 'e56cd59c65d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('password_hash', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('company_description', sa.String(length=1000), nullable=False))
        batch_op.add_column(sa.Column('phone', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('country', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('address', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('website', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('linkedin', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('creation_date', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint(None, ['company_name'])
        batch_op.create_unique_constraint(None, ['phone'])
        batch_op.drop_column('is_active')
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('creation_date')
        batch_op.drop_column('linkedin')
        batch_op.drop_column('website')
        batch_op.drop_column('address')
        batch_op.drop_column('country')
        batch_op.drop_column('phone')
        batch_op.drop_column('company_description')
        batch_op.drop_column('password_hash')
        batch_op.drop_column('company_name')

    # ### end Alembic commands ###
