"""empty message

Revision ID: da02d69acb54
Revises: e23d8440b3e2
Create Date: 2023-08-24 02:09:40.458043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da02d69acb54'
down_revision = 'e23d8440b3e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.alter_column('job_description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=2000),
               existing_nullable=False)
        batch_op.alter_column('job_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('experience_level',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.alter_column('experience_level',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('job_type',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('job_description',
               existing_type=sa.String(length=2000),
               type_=sa.TEXT(),
               existing_nullable=False)

    # ### end Alembic commands ###
