"""empty message

Revision ID: e23d8440b3e2
Revises: 6576ea50d75d
Create Date: 2023-08-24 01:49:31.162145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e23d8440b3e2'
down_revision = '6576ea50d75d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_title', sa.String(length=255), nullable=False),
    sa.Column('job_description', sa.Text(), nullable=False),
    sa.Column('skills', sa.String(length=255), nullable=False),
    sa.Column('job_type', sa.String(length=20), nullable=True),
    sa.Column('pay_rate', sa.Float(), nullable=True),
    sa.Column('experience_level', sa.String(length=20), nullable=True),
    sa.Column('questions', sa.Text(), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('company_website', sa.String(length=255), nullable=False),
    sa.Column('company_country', sa.String(length=100), nullable=False),
    sa.Column('company_state', sa.String(length=100), nullable=False),
    sa.Column('company_city', sa.String(length=100), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job')
    # ### end Alembic commands ###
